memory: 500M
cpu: 10%
disk: 200M
services:
  - name: python_server
    command: python -m wsgiref.simple_server
    restart:
      interval: 60
      limit: 5
endpoints:
  - name: http
    port: 5108
    type: infra

